POST  http://localhost:6000/api/car
Content-Type: application/json

{
    "name": "vinfast",
    "description": "test",
    "failure": "mới",
    "licensePlate": "123",
    "type": "4 chỗ",
    "company": "VinGroup",
    "status": false,
    "price": "500000"
}